const API_BASE = window.FLAGBOARD_API_BASE || "http://localhost:8000";
const state = { token: localStorage.getItem("flagboard_token"), email: localStorage.getItem("flagboard_email") || "", organizations: [], projects: [], flags: [], audits: [], selectedOrg: null, selectedProject: null, selectedFlag: null, socket: null, socketOrgId: null, socketReconnectTimer: null, socketClosing: false, authMode: "login" };

const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
const shortId = (value) => value ? `${value.slice(0, 8)}…` : "—";
const formatTime = (value) => value ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "—";

async function api(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } });
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || `Request failed (${response.status})`); }
  return response.status === 204 ? null : response.json();
}

function showDashboard() { $("#login-view").classList.add("is-hidden"); $("#dashboard-view").classList.remove("is-hidden"); $("#user-email").textContent = state.email; $("#sidebar-email").textContent = state.email; }
function showLogin() { $("#dashboard-view").classList.add("is-hidden"); $("#login-view").classList.remove("is-hidden"); }
function toast(message) { const element = $("#toast"); element.textContent = message; element.classList.add("show"); window.clearTimeout(toast.timeout); toast.timeout = window.setTimeout(() => element.classList.remove("show"), 2800); }
function setConnection(connected, label = connected ? "Live sync: connected" : "Live sync: unavailable") { $("#connection-dot").style.background = connected ? "var(--green)" : "#a6afaa"; $("#connection-label").textContent = label; }

function setAuthMode(mode) {
  state.authMode = mode; const signup = mode === "signup";
  $("#auth-title").innerHTML = signup ? "Start your<br /><span>workspace.</span>" : "Ship with<br /><span>confidence.</span>";
  $("#login-form button[type=submit]").innerHTML = signup ? "Create account <span aria-hidden=\"true\">→</span>" : "Sign in <span aria-hidden=\"true\">→</span>";
  $("#auth-switch").textContent = signup ? "Already have an account? Sign in" : "Need an account? Sign up";
  $("#password").autocomplete = signup ? "new-password" : "current-password"; $("#login-error").textContent = "";
}

async function login(event) {
  event.preventDefault(); const error = $("#login-error"); error.textContent = "";
  try { const endpoint = state.authMode === "signup" ? "/auth/signup" : "/auth/login"; const data = await api(endpoint, { method: "POST", body: JSON.stringify({ email: $("#email").value, password: $("#password").value }) }); state.token = data.access_token; state.email = $("#email").value.trim().toLowerCase(); localStorage.setItem("flagboard_token", state.token); localStorage.setItem("flagboard_email", state.email); showDashboard(); await loadOrganizations(); }
  catch (err) { error.textContent = err.message; }
}

function openOrgModal() { $("#org-modal").classList.remove("is-hidden"); $("#org-name-input").focus(); }
function closeOrgModal() { $("#org-modal").classList.add("is-hidden"); $("#org-form").reset(); $("#org-error").textContent = ""; }
async function createOrganization(event) { event.preventDefault(); $("#org-error").textContent = ""; try { await api("/orgs", { method: "POST", body: JSON.stringify({ name: $("#org-name-input").value }) }); closeOrgModal(); await loadOrganizations(); toast("Organization created"); } catch (err) { $("#org-error").textContent = err.message; } }

async function loadOrganizations() {
  state.organizations = await api("/orgs"); $("#org-list").innerHTML = state.organizations.map((org) => `<button class="org-button ${state.selectedOrg?.id === org.id ? "active" : ""}" data-org="${org.id}">${escapeHtml(org.name)}</button>`).join("");
  document.querySelectorAll("[data-org]").forEach((button) => button.addEventListener("click", () => selectOrganization(button.dataset.org)));
  if (state.organizations.length) await selectOrganization(state.selectedOrg?.id || state.organizations[0].id); else { $("#org-name").textContent = "No organizations"; $("#project-list").innerHTML = ""; renderEmpty("Create an organization to start managing flags."); }
}

async function selectOrganization(id) {
  state.selectedOrg = state.organizations.find((org) => org.id === id); $("#org-name").textContent = state.selectedOrg?.name || "Workspace"; document.querySelectorAll("[data-org]").forEach((button) => button.classList.toggle("active", button.dataset.org === id));
  state.projects = await api(`/orgs/${id}/projects`); $("#project-list").innerHTML = state.projects.map((project) => `<button class="project-button ${state.selectedProject?.id === project.id ? "active" : ""}" data-project="${project.id}">${escapeHtml(project.name)}</button>`).join(""); document.querySelectorAll("[data-project]").forEach((button) => button.addEventListener("click", () => selectProject(button.dataset.project)));
  if (state.projects.length) await selectProject(state.selectedProject?.organization_id === id ? state.selectedProject.id : state.projects[0].id); else { $("#project-context").textContent = "No projects in this organization."; renderEmpty("Create a project to start managing flags."); }
  connectSocket(id);
}

async function selectProject(id) { state.selectedProject = state.projects.find((project) => project.id === id); document.querySelectorAll("[data-project]").forEach((button) => button.classList.toggle("active", button.dataset.project === id)); $("#project-context").textContent = state.selectedProject ? `${state.selectedProject.key} · ${state.selectedProject.name}` : ""; await loadFlags(); }

async function loadFlags() { state.flags = await api(`/projects/${state.selectedProject.id}/flags`); renderFlags(); if (state.flags[0]) await selectFlag(state.selectedFlag?.id && state.flags.some((flag) => flag.id === state.selectedFlag.id) ? state.selectedFlag.id : state.flags[0].id); else { state.selectedFlag = null; renderAudit([]); } }
function currentEnvironment(flag) { return flag.environments.find((item) => item.environment === $("#environment").value) || flag.environments[0]; }
function renderFlags() { $("#flag-count").textContent = `${state.flags.length} ${state.flags.length === 1 ? "flag" : "flags"}`; $("#flag-list").innerHTML = state.flags.length ? state.flags.map((flag) => { const config = currentEnvironment(flag); return `<div class="flag-row"><div class="flag-main"><strong>${escapeHtml(flag.name)}</strong><span class="flag-key">${escapeHtml(flag.key)}</span></div><div class="flag-status ${config?.enabled ? "on" : "off"}"><span class="status-dot"></span>${config?.enabled ? "Enabled" : "Disabled"}</div><div class="rollout">${config?.rollout_percentage == null ? "100% rollout" : `${config.rollout_percentage}% rollout`}</div><button class="small-action" type="button" data-configure="${flag.id}">Configure</button><button class="switch" type="button" role="switch" aria-checked="${Boolean(config?.enabled)}" aria-label="Toggle ${escapeHtml(flag.name)}" data-flag="${flag.id}"></button></div>`; }).join("") : `<div class="empty-state">No flags in this project.</div>`; document.querySelectorAll("[data-flag]").forEach((button) => button.addEventListener("click", () => toggleFlag(button.dataset.flag, button))); document.querySelectorAll("[data-configure]").forEach((button) => button.addEventListener("click", () => openFlagConfig(button.dataset.configure))); }

async function toggleFlag(id, button) { const flag = state.flags.find((item) => item.id === id); const config = currentEnvironment(flag); button.disabled = true; try { const updated = await api(`/flags/${id}/environments/${$("#environment").value}/toggle`, { method: "PATCH", body: JSON.stringify({ enabled: !config.enabled }) }); const index = state.flags.findIndex((item) => item.id === id); state.flags[index] = updated; renderFlags(); await selectFlag(id); toast(`${flag.name} ${!config.enabled ? "enabled" : "disabled"}`); } catch (err) { toast(err.message); button.disabled = false; } }

async function selectFlag(id) { state.selectedFlag = state.flags.find((flag) => flag.id === id); if (!state.selectedFlag) return; try { state.audits = await api(`/flags/${id}/audit-log`); renderAudit(state.audits); } catch (err) { renderAudit([]); toast(err.message); } }
function renderAudit(audits) { $("#audit-list").innerHTML = audits.length ? audits.slice(0, 12).map((entry) => `<tr><td>${escapeHtml(entry.action.replaceAll("_", " "))}</td><td class="mono">${escapeHtml(state.selectedFlag?.key || shortId(entry.flag_id))}</td><td class="mono">${shortId(entry.actor_user_id)}</td><td class="mono">${formatTime(entry.created_at)}</td><td class="mono">${escapeHtml(summary(entry))}</td></tr>`).join("") : `<tr><td colspan="5" class="table-empty">No audit entries for this flag yet.</td></tr>`; }
function summary(entry) { const before = entry.before?.enabled; const after = entry.after?.enabled; if (typeof after === "boolean" && before !== after) return `${before ? "on" : "off"} → ${after ? "on" : "off"}`; return entry.after?.environment ? `${entry.after.environment}` : "Configuration updated"; }

function openModal(title, content) { $("#modal-title").textContent = title; $("#modal-content").innerHTML = content; $("#modal").classList.remove("is-hidden"); }
function closeModal() { $("#modal").classList.add("is-hidden"); $("#modal-content").innerHTML = ""; }
function modalForm(form) { form.addEventListener("submit", async (event) => { event.preventDefault(); const submit = form.querySelector("button[type=submit]"); if (submit) submit.disabled = true; try { const closeAfterSubmit = await form._submit(new FormData(form)); if (closeAfterSubmit !== false) closeModal(); } catch (error) { const target = form.querySelector(".form-error"); if (target) target.textContent = error.message; } finally { if (submit) submit.disabled = false; } }); }
function openCreateProject() { if (!state.selectedOrg) return toast("Create or select an organization first"); openModal("Create project", `<form id="project-form" class="modal-form"><label>Project name</label><input name="name" placeholder="Storefront" required /><label>Project key</label><input name="key" placeholder="storefront" required /><p class="form-error"></p><div class="modal-actions"><button class="button button-quiet" type="button" data-close-modal>Cancel</button><button class="button button-primary" type="submit">Create project <span>→</span></button></div></form>`); const form = $("#project-form"); form._submit = async (data) => { await api(`/orgs/${state.selectedOrg.id}/projects`, { method: "POST", body: JSON.stringify({ name: data.get("name"), key: data.get("key") }) }); await selectOrganization(state.selectedOrg.id); toast("Project created"); }; modalForm(form); }
function openCreateFlag() { if (!state.selectedProject) return toast("Select a project first"); openModal("Create feature flag", `<form id="flag-form" class="modal-form"><label>Flag name</label><input name="name" placeholder="New checkout flow" required /><label>Flag key</label><input name="key" placeholder="new_checkout_flow" required /><p class="form-error"></p><div class="modal-actions"><button class="button button-quiet" type="button" data-close-modal>Cancel</button><button class="button button-primary" type="submit">Create flag <span>→</span></button></div></form>`); const form = $("#flag-form"); form._submit = async (data) => { await api(`/projects/${state.selectedProject.id}/flags`, { method: "POST", body: JSON.stringify({ name: data.get("name"), key: data.get("key") }) }); await loadFlags(); toast("Flag created"); }; modalForm(form); }
function openFlagConfig(id) { const flag = state.flags.find((item) => item.id === id); const config = currentEnvironment(flag); openModal(`Configure ${flag.name}`, `<form id="config-form" class="modal-form"><p class="modal-context">${escapeHtml($("#environment").value)} · ${escapeHtml(flag.key)}</p><label>Rollout percentage</label><input name="percentage" type="number" min="0" max="100" value="${config.rollout_percentage ?? 100}" required /><label>Targeting rule attribute</label><input name="attribute" value="${escapeHtml(config.rule_attribute || "")}" placeholder="plan" /><label>Targeting rule value</label><input name="value" value="${escapeHtml(config.rule_value || "")}" placeholder="pro" /><p class="helper-text">Leave both rule fields blank to clear targeting.</p><p class="form-error"></p><div class="modal-actions"><button class="button button-quiet" type="button" data-close-modal>Cancel</button><button class="button button-primary" type="submit">Save settings <span>→</span></button></div></form>`); const form = $("#config-form"); form._submit = async (data) => { const environment = $("#environment").value; await api(`/flags/${id}/environments/${environment}/rollout`, { method: "PATCH", body: JSON.stringify({ percentage: Number(data.get("percentage")) }) }); const attribute = String(data.get("attribute")).trim(); const value = String(data.get("value")).trim(); await api(`/flags/${id}/environments/${environment}/rule`, { method: "PATCH", body: JSON.stringify(attribute && value ? { attribute, operator: "equals", value } : null) }); await loadFlags(); toast("Flag settings updated"); }; modalForm(form); }
async function loadApiKeys() { const keys = await api(`/orgs/${state.selectedOrg.id}/api-keys`); openModal("API keys", `<div class="modal-list">${keys.length ? keys.map((key) => `<div class="list-row"><div><strong>${escapeHtml(key.key_prefix)}…</strong><span>${escapeHtml(key.environment)} · ${key.revoked_at ? "revoked" : "active"}</span></div>${key.revoked_at ? "" : `<button class="small-action danger" data-revoke-key="${key.id}">Revoke</button>`}</div>`).join("") : `<p class="empty-state">No API keys yet.</p>`}</div><form id="key-form" class="inline-form"><select name="environment"><option value="development">Development</option><option value="staging">Staging</option><option value="production">Production</option></select><button class="button button-primary" type="submit">Create key <span>→</span></button><p class="form-error"></p></form>`); const form = $("#key-form"); form._submit = async (data) => { const created = await api(`/orgs/${state.selectedOrg.id}/api-keys`, { method: "POST", body: JSON.stringify({ environment: data.get("environment") }) }); openModal("API key created", `<p>Copy this key now. It will not be shown again.</p><input value="${escapeHtml(created.raw_key)}" readonly /><div class="modal-actions"><button class="button button-primary" type="button" data-close-modal>Done</button></div>`); toast("API key created"); return false; }; modalForm(form); document.querySelectorAll("[data-revoke-key]").forEach((button) => button.addEventListener("click", async () => { await api(`/orgs/${state.selectedOrg.id}/api-keys/${button.dataset.revokeKey}`, { method: "DELETE" }); loadApiKeys(); toast("API key revoked"); })); }
async function inviteMember() { if (!state.selectedOrg) return toast("Create or select an organization first"); openModal("Invite organization member", `<form id="member-form" class="modal-form"><label>Email address</label><input name="email" type="email" placeholder="teammate@company.com" required /><label>Role</label><select name="role"><option value="member">Member</option><option value="owner">Owner</option></select><p class="helper-text">The user must already have a FlagBoard account.</p><p class="form-error"></p><div class="modal-actions"><button class="button button-quiet" type="button" data-close-modal>Cancel</button><button class="button button-primary" type="submit">Invite member <span>→</span></button></div></form>`); const form = $("#member-form"); form._submit = async (data) => { await api(`/orgs/${state.selectedOrg.id}/members`, { method: "POST", body: JSON.stringify({ email: data.get("email"), role: data.get("role") }) }); toast("Member invited"); }; modalForm(form); }
async function evaluateFlag() { if (!state.selectedFlag) return toast("Select a flag first"); const keys = await api(`/orgs/${state.selectedOrg.id}/api-keys`); const activeKeys = keys.filter((key) => !key.revoked_at); openModal("Evaluate flag", `<form id="evaluate-form" class="modal-form"><label>Evaluation API key</label><input name="apiKey" placeholder="Paste the raw API key" required /><p class="helper-text">Keys are only returned once when created. This request uses the selected environment.</p><label>User key</label><input name="userKey" value="demo-user" required /><label>Attributes (JSON)</label><textarea name="attributes">{"plan":"pro"}</textarea><p class="form-error"></p><div class="modal-actions"><button class="button button-quiet" type="button" data-close-modal>Cancel</button><button class="button button-primary" type="submit">Evaluate <span>→</span></button></div></form><p class="helper-text">${activeKeys.length} active key(s) available for this organization.</p>`); const form = $("#evaluate-form"); form._submit = async (data) => { let attributes; try { attributes = JSON.parse(data.get("attributes") || "{}"); } catch { throw new Error("Attributes must be valid JSON"); } const response = await api(`/evaluate/${encodeURIComponent(state.selectedFlag.key)}`, { method: "POST", headers: { Authorization: `ApiKey ${data.get("apiKey")}` }, body: JSON.stringify({ user: { key: data.get("userKey"), attributes } }) }); openModal("Evaluation result", `<div class="evaluation-result"><strong>${response.value ? "ON" : "OFF"}</strong><span>${escapeHtml(response.reason)}</span></div><div class="modal-actions"><button class="button button-primary" type="button" data-close-modal>Done</button></div>`); return false; }; modalForm(form); }

function connectSocket(orgId) {
  if (state.socket) { state.socketClosing = true; state.socket.close(); }
  window.clearTimeout(state.socketReconnectTimer); state.socketOrgId = orgId; state.socketClosing = false; setConnection(false, "Live sync: connecting…");
  const protocol = API_BASE.startsWith("https") ? "wss" : "ws"; const host = API_BASE.replace(/^https?:\/\//, ""); state.socket = new WebSocket(`${protocol}://${host}/ws/orgs/${orgId}?token=${encodeURIComponent(state.token)}`);
  state.socket.addEventListener("open", () => setConnection(true));
  state.socket.addEventListener("close", () => { if (!state.socketClosing && state.token && state.socketOrgId === orgId) { setConnection(false, "Live sync: retrying…"); state.socketReconnectTimer = window.setTimeout(() => connectSocket(orgId), 2500); } });
  state.socket.addEventListener("error", () => setConnection(false, "Live sync: unavailable"));
  state.socket.addEventListener("message", async () => { await loadFlags(); toast("Flag updated live"); });
}
function renderEmpty(message) { $("#flag-count").textContent = "—"; $("#flag-list").innerHTML = `<div class="empty-state">${escapeHtml(message)}</div>`; renderAudit([]); }

$("#login-form").addEventListener("submit", login);
$("#auth-switch").addEventListener("click", () => setAuthMode(state.authMode === "login" ? "signup" : "login"));
$("#create-org-button").addEventListener("click", openOrgModal);
$("#close-org-modal").addEventListener("click", closeOrgModal);
$("#cancel-org-modal").addEventListener("click", closeOrgModal);
$("#org-form").addEventListener("submit", createOrganization);
$("#org-modal").addEventListener("click", (event) => { if (event.target.id === "org-modal") closeOrgModal(); });
$("#create-project-button").addEventListener("click", openCreateProject);
$("#create-flag-button").addEventListener("click", openCreateFlag);
$("#keys-button").addEventListener("click", () => state.selectedOrg && loadApiKeys().catch((error) => toast(error.message)));
$("#members-button").addEventListener("click", inviteMember);
$("#evaluate-button").addEventListener("click", () => evaluateFlag().catch((error) => toast(error.message)));
$("#modal").addEventListener("click", (event) => { if (event.target.id === "modal" || event.target.matches("[data-close-modal]")) closeModal(); });
$("#logout-button").addEventListener("click", () => { state.socketClosing = true; if (state.socket) state.socket.close(); window.clearTimeout(state.socketReconnectTimer); localStorage.removeItem("flagboard_token"); localStorage.removeItem("flagboard_email"); state.token = null; showLogin(); });
$("#environment").addEventListener("change", () => { renderFlags(); if (state.selectedFlag) selectFlag(state.selectedFlag.id); });

if (state.token) { showDashboard(); loadOrganizations().catch(() => { localStorage.removeItem("flagboard_token"); localStorage.removeItem("flagboard_email"); state.token = null; showLogin(); }); }
