const API_BASE = window.FLAGBOARD_API_BASE || "http://localhost:8000";
const stored = JSON.parse(localStorage.getItem("flagboard_demo") || "{}");
const state = { apiKey:stored.apiKey || "", flagKey:stored.flagKey || "new_checkout_flow", plan:"pro", value:null, requestInFlight:false };
const $ = (selector) => document.querySelector(selector);
const apiKeyInput = $("#api-key"); const flagKeyInput = $("#flag-key"); apiKeyInput.value = state.apiKey; flagKeyInput.value = state.flagKey;
function setMessage(message, isError=false) { $("#connection-message").textContent=message; $("#connection-message").classList.toggle("error",isError); }
function renderExperience() { const enabled=state.value===true; const badge=$("#experience-badge"); badge.textContent=enabled?"New experience · ON":state.value===false?"Classic experience · OFF":"Waiting for connection"; badge.classList.toggle("off",!enabled); $("#checkout-content").innerHTML=enabled?`<h2>A faster way to pay.</h2><p>You are seeing the new checkout because this customer is included by the current FlagBoard configuration.</p><button class="checkout-button" type="button">Pay securely <span>→</span></button>`:`<h2>The familiar checkout.</h2><p>This is the safe, classic checkout experience. Turn the feature flag on in FlagBoard to release the redesigned flow.</p><button class="checkout-button classic" type="button">Continue to payment <span>→</span></button>`; }
async function evaluate(showMessage=false) { if(!state.apiKey||!state.flagKey||state.requestInFlight)return; state.requestInFlight=true; try { const response=await fetch(`${API_BASE}/evaluate/${encodeURIComponent(state.flagKey)}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`ApiKey ${state.apiKey}`},body:JSON.stringify({user:{key:"demo-customer-123",attributes:{plan:state.plan}}})}); const data=await response.json().catch(()=>({})); if(!response.ok)throw new Error(data.detail||`Evaluation failed (${response.status})`); const changed=state.value!==data.value; state.value=data.value; renderExperience(); $("#last-checked").textContent=`Last checked ${new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit",second:"2-digit"})}`; setMessage(`Flag result: ${data.value?"ON":"OFF"} · ${data.reason}${changed?" · experience updated":""}`); if(showMessage)setMessage(`Connected · ${data.flag_key} is ${data.value?"ON":"OFF"} (${data.reason})`); } catch(error) { setMessage(error.message,true); } finally { state.requestInFlight=false; } }
function connect(event) { event.preventDefault(); state.apiKey=apiKeyInput.value.trim(); state.flagKey=flagKeyInput.value.trim(); localStorage.setItem("flagboard_demo",JSON.stringify({apiKey:state.apiKey,flagKey:state.flagKey})); state.value=null; renderExperience(); evaluate(true); window.clearInterval(state.timer); state.timer=window.setInterval(()=>evaluate(),1500); }
$("#connection-form").addEventListener("submit",connect); document.querySelectorAll("[data-plan]").forEach((button)=>button.addEventListener("click",()=>{ state.plan=button.dataset.plan; document.querySelectorAll("[data-plan]").forEach((item)=>item.classList.toggle("active",item===button)); evaluate(true); })); renderExperience(); if(state.apiKey){ evaluate(true); state.timer=window.setInterval(()=>evaluate(),1500); }
